project_id = "oqrvskdtvaykqkclpgew"

[functions.submit-patient-application]
verify_jwt = false

[functions.test-mailjet]
verify_jwt = false

[functions.realtime-voice-token]
verify_jwt = false

[functions.log-provider-search]
verify_jwt = false
